version: "2"
checks:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: rulesets.xml
  similar-code:
    config:
      threshold: 64
exclude_patterns:
  - "**/tests/**"
