pug-php/pug: default

pug/bemto: default

pug-php/pug-assets: default

pug-php/pug-minify: default

pug/slim: default

pug/twig:
  autoload:
    - cp -r vendor/phug/phug vendor/phug/compiler
    - composer dump-autoload --optimize --no-interaction --quiet

ci-pug/ci-pug: default

bkwld/laravel-pug: default

pug/yii2: default
