
language: php

git:
  depth: 5

env:
  global:
    - COMPOSER_FLAGS=''
    - CODACY_PROJECT_TOKEN=eb1f0554c46a4ae486c35d40f75b6d4e
    - CC_TEST_REPORTER_ID=cd1a1fbecb6b26000bcdc53d59b592735acb420dd96ce7151cd9424c39c95cf3
    - MULTITEST=off
    - COVERAGE=off
    - STYLECHECK=off
    - SPLIT=off

matrix:
  include:
    - php: nightly
    - php: 7.4
    - php: 7.3
      env: COVERAGE=on
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      dist: trusty
    - php: 7.3
      env: STYLECHECK=on
    - php: 7.3
      env: MULTITEST=on
    - php: 7.3
      env: SPLIT=on

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

sudo: false

install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^nightly ]]; then COMPOSER_FLAGS='--ignore-platform-reqs'; fi
  - if [[ "$COVERAGE" != "on" ]]; then phpenv config-rm xdebug.ini || echo 'XDebug already disabled'; fi;
  - travis_retry composer self-update
  - composer config version 1.0.x-dev
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction

before_script:
  - if [[ "$COVERAGE" = "on" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi;
  - if [[ "$COVERAGE" = "on" ]]; then chmod +x ./cc-test-reporter; fi;
  - if [[ "$COVERAGE" = "on" ]]; then ./cc-test-reporter before-build; fi;

script:
  - if [[ "$STYLECHECK" != "on" && "$COVERAGE" != "on" && "$MULTITEST" != "on" && "$SPLIT" != "on" ]]; then vendor/bin/phpunit; fi;
  - if [[ "$COVERAGE" = "on" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml; fi;
  - if [[ "$MULTITEST" = "on" ]]; then vendor/bin/multi-tester --verbose --quiet-install; fi;
  - if [[ "$STYLECHECK" = "on" ]]; then vendor/bin/phpcs --ignore=*.js src; fi;
  - if [[ "$SPLIT" = "on" ]]; then composer require phug/split && vendor/bin/split update --git-credentials=$GH_CREDENTIALS; fi;

after_success:
  - if [[ "$COVERAGE" = "on" ]]; then bash <(curl -s https://codecov.io/bash); fi;

after_script:
  - if [[ "$COVERAGE" = "on" ]]; then cp coverage.xml clover.xml; fi;
  - if [[ "$COVERAGE" = "on" ]]; then ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT; fi;
  - if [[ "$COVERAGE" = "on" ]]; then composer require codacy/coverage; fi;
  - if [[ "$COVERAGE" = "on" ]]; then vendor/bin/codacycoverage clover coverage.xml; fi;

notifications:
  slack: phug:nzXFnxhU14RWK2EQSDL0u08z
